media: media
content:
  - name: pages
    label: Pages
    type: collection
    path: docs
    fields:
      - name: title
        type: string
      - name: Anforderung
        type: string
      - name: Process
        type: string
      - name: status
        type: select
        options:
          values: [Draft, Review, Published]
      - name: requirements
        type: reference
        options:
          collection: requirements
          multiple: true
          min: 1
          max: 5
      - name: body
        type: rich-text
  - name: requirements
    label: Requirements
    type: collection
    path: requirements
    fields:
      - name: title
        type: string
      - name: Anforderung
        type: string
      - name: Process
        type: string
      - name: status
        type: select
        options:
          values: [Draft, Review, Published]
      - name: body
        type: rich-text
